// This enum was generated by Dialoguer
//	Do not modify this file, it will be overwritten by Dialoguer.
public enum DialoguerDialogues{
	Bennet_Yard_0 = 0,
	Bennet_Yard_1 = 1,
	Liddy_Yard_0 = 2,
	Kitty_Yard_0 = 3,
	Liddy_Yard_1 = 4,
}
